name: opensea-pipeline
services:
  os-pyspark-jupyter:
    image: jupyter/pyspark-notebook:spark-3.3.0
    user: root
    container_name: os-pyspark-jupyter-lab
    ports:
      - 9888:8888
      - 4140:4040
    environment:
      JUPYTER_PORT: 8888
      SPARK_UI_PORT: 4040
      GRANT_SUDO: yes
    volumes:
      - os-streaming_data:/data:rw
  os-spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: os-spark-master
    ports:
      - "8180:8080"
      - "7177:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
        - os-spark_data:/data:rw
  os-spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: os-spark-worker-1
    depends_on:
      - os-spark-master
    ports:
      - "8181:8081"
    environment:
      - "SPARK_MASTER=spark://os-spark-master:7077"
    volumes:
        - os-spark_data:/data:rw
  os-spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: os-spark-worker-2
    depends_on:
      - os-spark-master
    ports:
      - "8182:8081"
    environment:
      - "SPARK_MASTER=spark://os-spark-master:7077"
    volumes:
        - os-spark_data:/data:rw
  os-spark-history-server:
      image: bde2020/spark-history-server:3.3.0-hadoop3.3
      container_name: os-spark-history-server
      depends_on:
        - os-spark-master
      ports:
        - "18181:18081"
      volumes:
        - /tmp/os-spark-events-local:/tmp/spark-events
volumes:
  os-streaming_data:
  os-spark_data:

networks:
  default:
    name: opensea-pipeline-network