name: opensea-pipeline
services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: os-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@os-kafka:9096"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9097,CONTROLLER://0.0.0.0:9096
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://os-kafka:9092,OUTSIDE://localhost:9097
      KAFKA_ADVERTISED_HOST_NAME: "os-kafka"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: "5Yr1SIgZRy-c-dgRabWy3f"
    ports:
      - "9095:9092"  # Internal Docker network (optional to expose)
      - "9096:9096"  # Controller listener port
      - "9097:9097"  # External access on localhost
    volumes:
      - kafka-data-opensea:/tmp/kraft-combined-logs
    user: "root"

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.4.0
    container_name: os-kafka-connect
    ports:
      - "8084:8084"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "os-kafka:9095"
      CONNECT_REST_PORT: 8084
      CONNECT_GROUP_ID: "connect-cluster-opensea"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs-opensea"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets-opensea"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status-opensea"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect-opensea"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/jars"
    volumes:
      - ./kafka-connect-plugins:/etc/kafka-connect/jars
      - C:/hadoop:/opt/hadoop
    depends_on:
      - kafka

volumes:
  kafka-data-opensea:

networks:
  default:
    name: opensea-pipeline-net